### ISSUE TITLE
add a price

### ISSUE THREAD

**Issue by sh4msi** [mckenziearts/shopper#20]
Hello
How do I add a price? And attributes like color and size?

**Comment by mckenziearts** [comment]
Hi @sh4msi to add a price to a product you should create your product first, after that you can slide to the offers tab to add one or more offer to your product to have something like this :

`iPhone X | 250Go($850.50) - 64Go ($499.84) - ...`

![ezgif-5-269d47358944](https://user-images.githubusercontent.com/14105989/64407561-8658cf00-d07c-11e9-9a91-5ac5ae3a24fe.gif)
 
For the attributes like `color` or `size` WIP
