### ISSUE TITLE
Custom Payment methods 

### ISSUE THREAD

**Issue by HomaEEE** [mckenziearts/shopper#4]
Hello. Can I create custom method for payment,  for example PayPal or another system. Client make order,  paid by choosed system and shop received callback from PayPal about transaction?

**Comment by fabriceyopa** [comment]
From now you dit not real implemented Payment method. But soon Stripe and Paypal will be available

**Comment by yuceltoluyag** [comment]
https://github.com/iyzico/iyzipay-laravel  you can add it to your project
