### ISSUE TITLE
Algolia error

### ISSUE THREAD

**Issue by picbenoit** [mckenziearts/shopper#7]
Hi @mckenziearts,

Everytime I created/updated a category/product I have an Agolia error appear.
I don't know Agolia and I don't want to use it for the moment. How can I config it for not apear next time ?

Thank you,

Ben

**Comment by mckenziearts** [comment]
Hi @picbenoit Laravel Shopper is build to work with algolia. Algolia is a api to improve the search on your store. look Algolia documentation [here](https://www.algolia.com/doc/)

**Comment by picbenoit** [comment]
Thank you for your answer.
Seems that algolia is not free, right ?
And my projects will not have so many products so searching will not be so complicated at the beginning. And also for the moment, this is just a project not a real shop.
I also see on Laravel docs (https://laravel.com/docs/5.8/scout) I can maybe made my own search implementation.

**Comment by mckenziearts** [comment]
That's right. Let me fix that on the next release.

**Comment by picbenoit** [comment]
Hi,
I tried and succeessed to install these package : https://github.com/teamtnt/laravel-scout-tntsearch-driver
It works fine with shopper and index all products / categories / searchable models

**Comment by mckenziearts** [comment]
Cool, Shopper integrate Laravel Scout and default is algolia is used. But you can change it
